services:
  kioku:
    image: ghcr.io/flipstone/haskell-tools:debian-unstable-ghc-9.2.7-2023-06-28-27bed39
    environment:
      IN_DEV_CONTAINER: 'true'
      STACK_ROOT: /stack-root
      # Pass through the CI variable from GitHub (or set it to `true` locally
      # for debugging CI builds)
      CI:
    volumes:
      - .:${PROJECT_DIR}
      - flipstone_stack_root:/stack-root
    working_dir: ${PROJECT_DIR}

volumes:
  flipstone_stack_root:
    external: true
