name: kioku
version: '0.1.3.1'
synopsis: A library for indexing and querying static datasets on disk
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
homepage: http://github.com/flipstone/kioku
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -fprof-auto
- -Werror
dependencies:
- base >=4.8
- bytestring
- zlib
library:
  source-dirs: src
  exposed-modules:
  - Database.Kioku
  - Database.Kioku.Core
  - Database.Kioku.Memorizable
  - Database.Kioku.Schema
  dependencies:
  - base16-bytestring
  - containers
  - cryptohash
  - directory
  - filepath
  - mmap
  - non-empty-text
  - vector
  - vector-algorithms >=0.8.0.1
  - reinterpret-cast
  - tar
  - temporary
  - text
executables:
  kioku-benchmarks:
    main: benchmarks/Main.hs
    ghc-options:
    - -O3
    - -rtsopts
    dependencies:
    - time
    - kioku
    - deepseq
  kioku-example:
    main: example/Main.hs
    default-extensions:
    - RecordWildCards
    ghc-options:
    - -O3
    dependencies:
    - kioku
tests:
  kioku-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
    - -O3
    dependencies:
      - kioku
      - containers
      - deepseq
      - tasty
      - tasty-discover
      - tasty-hunit
      - hedgehog
      - tasty-hedgehog
