name: Build and Test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Test
    runs-on:
      group: builder
      labels: [self-hosted, x64, builder]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        env:
          cache-version: v3
        with:
          key: ${{ env.cache-version }}-${{ hashFiles('stack*.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ env.cache-version }}-
          path: |
            ./stack-root

      - name: Build and test
        run: |
          set -e
          mkdir -p ./stack-root
          echo "PROJECT_DIR=$PWD" >> .env
          mv compose.override.github.yaml compose.override.yaml
          ./scripts/build
